# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/GimbalInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GimbalInfo(genpy.Message):
  _md5sum = "de1cd11d7e2cb10eb47cdbc531727f86"
  _type = "roborts_msgs/GimbalInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 ecd_yaw
float64 ecd_pitch
float64 gyro_yaw
float64 gyro_pitch
float64 yaw_rate
float64 pitch_rate
"""
  __slots__ = ['ecd_yaw','ecd_pitch','gyro_yaw','gyro_pitch','yaw_rate','pitch_rate']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ecd_yaw,ecd_pitch,gyro_yaw,gyro_pitch,yaw_rate,pitch_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GimbalInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ecd_yaw is None:
        self.ecd_yaw = 0.
      if self.ecd_pitch is None:
        self.ecd_pitch = 0.
      if self.gyro_yaw is None:
        self.gyro_yaw = 0.
      if self.gyro_pitch is None:
        self.gyro_pitch = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.pitch_rate is None:
        self.pitch_rate = 0.
    else:
      self.ecd_yaw = 0.
      self.ecd_pitch = 0.
      self.gyro_yaw = 0.
      self.gyro_pitch = 0.
      self.yaw_rate = 0.
      self.pitch_rate = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.ecd_yaw, _x.ecd_pitch, _x.gyro_yaw, _x.gyro_pitch, _x.yaw_rate, _x.pitch_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.ecd_yaw, _x.ecd_pitch, _x.gyro_yaw, _x.gyro_pitch, _x.yaw_rate, _x.pitch_rate,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.ecd_yaw, _x.ecd_pitch, _x.gyro_yaw, _x.gyro_pitch, _x.yaw_rate, _x.pitch_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.ecd_yaw, _x.ecd_pitch, _x.gyro_yaw, _x.gyro_pitch, _x.yaw_rate, _x.pitch_rate,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
