# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/GimbalPID.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GimbalPID(genpy.Message):
  _md5sum = "47363277c60e8bf4c4fc3528d560ba62"
  _type = "roborts_msgs/GimbalPID"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#detection to gimbal control
bool is_valid
bool yaw_mode
bool pitch_mode
float64 x
float64 y
float64 z
int32 undetected_count_
"""
  __slots__ = ['is_valid','yaw_mode','pitch_mode','x','y','z','undetected_count_']
  _slot_types = ['bool','bool','bool','float64','float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_valid,yaw_mode,pitch_mode,x,y,z,undetected_count_

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GimbalPID, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.is_valid is None:
        self.is_valid = False
      if self.yaw_mode is None:
        self.yaw_mode = False
      if self.pitch_mode is None:
        self.pitch_mode = False
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.undetected_count_ is None:
        self.undetected_count_ = 0
    else:
      self.is_valid = False
      self.yaw_mode = False
      self.pitch_mode = False
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.undetected_count_ = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B3di().pack(_x.is_valid, _x.yaw_mode, _x.pitch_mode, _x.x, _x.y, _x.z, _x.undetected_count_))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 31
      (_x.is_valid, _x.yaw_mode, _x.pitch_mode, _x.x, _x.y, _x.z, _x.undetected_count_,) = _get_struct_3B3di().unpack(str[start:end])
      self.is_valid = bool(self.is_valid)
      self.yaw_mode = bool(self.yaw_mode)
      self.pitch_mode = bool(self.pitch_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B3di().pack(_x.is_valid, _x.yaw_mode, _x.pitch_mode, _x.x, _x.y, _x.z, _x.undetected_count_))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 31
      (_x.is_valid, _x.yaw_mode, _x.pitch_mode, _x.x, _x.y, _x.z, _x.undetected_count_,) = _get_struct_3B3di().unpack(str[start:end])
      self.is_valid = bool(self.is_valid)
      self.yaw_mode = bool(self.yaw_mode)
      self.pitch_mode = bool(self.pitch_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B3di = None
def _get_struct_3B3di():
    global _struct_3B3di
    if _struct_3B3di is None:
        _struct_3B3di = struct.Struct("<3B3di")
    return _struct_3B3di
