// Generated by gencpp from file roborts_msgs/ArmorPos.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_ARMORPOS_H
#define ROBORTS_MSGS_MESSAGE_ARMORPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct ArmorPos_
{
  typedef ArmorPos_<ContainerAllocator> Type;

  ArmorPos_()
    : is_valid(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , distance(0.0)
    , pose_in_gimbal()
    , vertex()
    , motion_vec()  {
    }
  ArmorPos_(const ContainerAllocator& _alloc)
    : is_valid(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , distance(0.0)
    , pose_in_gimbal(_alloc)
    , vertex(_alloc)
    , motion_vec(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _distance_type;
  _distance_type distance;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_in_gimbal_type;
  _pose_in_gimbal_type pose_in_gimbal;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _vertex_type;
  _vertex_type vertex;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _motion_vec_type;
  _motion_vec_type motion_vec;





  typedef boost::shared_ptr< ::roborts_msgs::ArmorPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::ArmorPos_<ContainerAllocator> const> ConstPtr;

}; // struct ArmorPos_

typedef ::roborts_msgs::ArmorPos_<std::allocator<void> > ArmorPos;

typedef boost::shared_ptr< ::roborts_msgs::ArmorPos > ArmorPosPtr;
typedef boost::shared_ptr< ::roborts_msgs::ArmorPos const> ArmorPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::ArmorPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::ArmorPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ArmorPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ArmorPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ArmorPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c1653860dd6778fef70d70be834958c";
  }

  static const char* value(const ::roborts_msgs::ArmorPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c1653860dd6778fULL;
  static const uint64_t static_value2 = 0xef70d70be834958cULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/ArmorPos";
  }

  static const char* value(const ::roborts_msgs::ArmorPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_valid\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 distance\n\
float64[] pose_in_gimbal\n\
float64[] vertex\n\
float64[] motion_vec\n\
";
  }

  static const char* value(const ::roborts_msgs::ArmorPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_valid);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.distance);
      stream.next(m.pose_in_gimbal);
      stream.next(m.vertex);
      stream.next(m.motion_vec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmorPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::ArmorPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::ArmorPos_<ContainerAllocator>& v)
  {
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "pose_in_gimbal[]" << std::endl;
    for (size_t i = 0; i < v.pose_in_gimbal.size(); ++i)
    {
      s << indent << "  pose_in_gimbal[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_in_gimbal[i]);
    }
    s << indent << "vertex[]" << std::endl;
    for (size_t i = 0; i < v.vertex.size(); ++i)
    {
      s << indent << "  vertex[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vertex[i]);
    }
    s << indent << "motion_vec[]" << std::endl;
    for (size_t i = 0; i < v.motion_vec.size(); ++i)
    {
      s << indent << "  motion_vec[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.motion_vec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_ARMORPOS_H
