// Generated by gencpp from file roborts_msgs/BallCollision.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_BALLCOLLISION_H
#define ROBORTS_MSGS_MESSAGE_BALLCOLLISION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct BallCollision_
{
  typedef BallCollision_<ContainerAllocator> Type;

  BallCollision_()
    : collision_time(0.0)
    , collision_1()
    , collision_2()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  BallCollision_(const ContainerAllocator& _alloc)
    : collision_time(0.0)
    , collision_1(_alloc)
    , collision_2(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _collision_time_type;
  _collision_time_type collision_time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _collision_1_type;
  _collision_1_type collision_1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _collision_2_type;
  _collision_2_type collision_2;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::roborts_msgs::BallCollision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::BallCollision_<ContainerAllocator> const> ConstPtr;

}; // struct BallCollision_

typedef ::roborts_msgs::BallCollision_<std::allocator<void> > BallCollision;

typedef boost::shared_ptr< ::roborts_msgs::BallCollision > BallCollisionPtr;
typedef boost::shared_ptr< ::roborts_msgs::BallCollision const> BallCollisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::BallCollision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::BallCollision_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::BallCollision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::BallCollision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::BallCollision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::BallCollision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::BallCollision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::BallCollision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::BallCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3495fecab5c6286c1b0aa9239dbe76b";
  }

  static const char* value(const ::roborts_msgs::BallCollision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3495fecab5c6286ULL;
  static const uint64_t static_value2 = 0xc1b0aa9239dbe76bULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::BallCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/BallCollision";
  }

  static const char* value(const ::roborts_msgs::BallCollision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::BallCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 collision_time\n\
string collision_1\n\
string collision_2\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
";
  }

  static const char* value(const ::roborts_msgs::BallCollision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::BallCollision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collision_time);
      stream.next(m.collision_1);
      stream.next(m.collision_2);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallCollision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::BallCollision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::BallCollision_<ContainerAllocator>& v)
  {
    s << indent << "collision_time: ";
    Printer<double>::stream(s, indent + "  ", v.collision_time);
    s << indent << "collision_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.collision_1);
    s << indent << "collision_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.collision_2);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_BALLCOLLISION_H
