// Generated by gencpp from file roborts_msgs/DodgeMode.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_DODGEMODE_H
#define ROBORTS_MSGS_MESSAGE_DODGEMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct DodgeMode_
{
  typedef DodgeMode_<ContainerAllocator> Type;

  DodgeMode_()
    : is_dodge(false)  {
    }
  DodgeMode_(const ContainerAllocator& _alloc)
    : is_dodge(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_dodge_type;
  _is_dodge_type is_dodge;





  typedef boost::shared_ptr< ::roborts_msgs::DodgeMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::DodgeMode_<ContainerAllocator> const> ConstPtr;

}; // struct DodgeMode_

typedef ::roborts_msgs::DodgeMode_<std::allocator<void> > DodgeMode;

typedef boost::shared_ptr< ::roborts_msgs::DodgeMode > DodgeModePtr;
typedef boost::shared_ptr< ::roborts_msgs::DodgeMode const> DodgeModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::DodgeMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::DodgeMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::DodgeMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::DodgeMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::DodgeMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e86a3c0123103abb455aca69f2a22f53";
  }

  static const char* value(const ::roborts_msgs::DodgeMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe86a3c0123103abbULL;
  static const uint64_t static_value2 = 0x455aca69f2a22f53ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/DodgeMode";
  }

  static const char* value(const ::roborts_msgs::DodgeMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_dodge\n\
";
  }

  static const char* value(const ::roborts_msgs::DodgeMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_dodge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DodgeMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::DodgeMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::DodgeMode_<ContainerAllocator>& v)
  {
    s << indent << "is_dodge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_dodge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_DODGEMODE_H
