// Generated by gencpp from file roborts_msgs/FusionTarget.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_FUSIONTARGET_H
#define ROBORTS_MSGS_MESSAGE_FUSIONTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roborts_msgs/Target.h>
#include <roborts_msgs/Target.h>

namespace roborts_msgs
{
template <class ContainerAllocator>
struct FusionTarget_
{
  typedef FusionTarget_<ContainerAllocator> Type;

  FusionTarget_()
    : num_id_target(0)
    , num_no_id_target(0)
    , id_targets()
    , no_id_targets()  {
    }
  FusionTarget_(const ContainerAllocator& _alloc)
    : num_id_target(0)
    , num_no_id_target(0)
    , id_targets(_alloc)
    , no_id_targets(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _num_id_target_type;
  _num_id_target_type num_id_target;

   typedef uint8_t _num_no_id_target_type;
  _num_no_id_target_type num_no_id_target;

   typedef std::vector< ::roborts_msgs::Target_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roborts_msgs::Target_<ContainerAllocator> >::other >  _id_targets_type;
  _id_targets_type id_targets;

   typedef std::vector< ::roborts_msgs::Target_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roborts_msgs::Target_<ContainerAllocator> >::other >  _no_id_targets_type;
  _no_id_targets_type no_id_targets;





  typedef boost::shared_ptr< ::roborts_msgs::FusionTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::FusionTarget_<ContainerAllocator> const> ConstPtr;

}; // struct FusionTarget_

typedef ::roborts_msgs::FusionTarget_<std::allocator<void> > FusionTarget;

typedef boost::shared_ptr< ::roborts_msgs::FusionTarget > FusionTargetPtr;
typedef boost::shared_ptr< ::roborts_msgs::FusionTarget const> FusionTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::FusionTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::FusionTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::FusionTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::FusionTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::FusionTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b446fdc6c26040d3eceffafbf5e0975";
  }

  static const char* value(const ::roborts_msgs::FusionTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b446fdc6c26040dULL;
  static const uint64_t static_value2 = 0x3eceffafbf5e0975ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/FusionTarget";
  }

  static const char* value(const ::roborts_msgs::FusionTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 num_id_target\n\
uint8 num_no_id_target\n\
Target[] id_targets\n\
Target[] no_id_targets\n\
\n\
================================================================================\n\
MSG: roborts_msgs/Target\n\
uint8 id\n\
uint8 state\n\
uint8 sensor\n\
float32 x\n\
float32 y\n\
float32 confidence\n\
";
  }

  static const char* value(const ::roborts_msgs::FusionTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_id_target);
      stream.next(m.num_no_id_target);
      stream.next(m.id_targets);
      stream.next(m.no_id_targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FusionTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::FusionTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::FusionTarget_<ContainerAllocator>& v)
  {
    s << indent << "num_id_target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_id_target);
    s << indent << "num_no_id_target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_no_id_target);
    s << indent << "id_targets[]" << std::endl;
    for (size_t i = 0; i < v.id_targets.size(); ++i)
    {
      s << indent << "  id_targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roborts_msgs::Target_<ContainerAllocator> >::stream(s, indent + "    ", v.id_targets[i]);
    }
    s << indent << "no_id_targets[]" << std::endl;
    for (size_t i = 0; i < v.no_id_targets.size(); ++i)
    {
      s << indent << "  no_id_targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roborts_msgs::Target_<ContainerAllocator> >::stream(s, indent + "    ", v.no_id_targets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_FUSIONTARGET_H
