// Generated by gencpp from file roborts_msgs/FVector.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_FVECTOR_H
#define ROBORTS_MSGS_MESSAGE_FVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct FVector_
{
  typedef FVector_<ContainerAllocator> Type;

  FVector_()
    : vector()  {
    }
  FVector_(const ContainerAllocator& _alloc)
    : vector(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vector_type;
  _vector_type vector;





  typedef boost::shared_ptr< ::roborts_msgs::FVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::FVector_<ContainerAllocator> const> ConstPtr;

}; // struct FVector_

typedef ::roborts_msgs::FVector_<std::allocator<void> > FVector;

typedef boost::shared_ptr< ::roborts_msgs::FVector > FVectorPtr;
typedef boost::shared_ptr< ::roborts_msgs::FVector const> FVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::FVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::FVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::FVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::FVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::FVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::FVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::FVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::FVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::FVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce95c8b6ee55a22d6d20b2422ec7f431";
  }

  static const char* value(const ::roborts_msgs::FVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce95c8b6ee55a22dULL;
  static const uint64_t static_value2 = 0x6d20b2422ec7f431ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::FVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/FVector";
  }

  static const char* value(const ::roborts_msgs::FVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::FVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] vector\n\
";
  }

  static const char* value(const ::roborts_msgs::FVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::FVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::FVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::FVector_<ContainerAllocator>& v)
  {
    s << indent << "vector[]" << std::endl;
    for (size_t i = 0; i < v.vector.size(); ++i)
    {
      s << indent << "  vector[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_FVECTOR_H
