// Generated by gencpp from file roborts_msgs/GimbalInfo.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GIMBALINFO_H
#define ROBORTS_MSGS_MESSAGE_GIMBALINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct GimbalInfo_
{
  typedef GimbalInfo_<ContainerAllocator> Type;

  GimbalInfo_()
    : ecd_yaw(0.0)
    , ecd_pitch(0.0)
    , gyro_yaw(0.0)
    , gyro_pitch(0.0)
    , yaw_rate(0.0)
    , pitch_rate(0.0)  {
    }
  GimbalInfo_(const ContainerAllocator& _alloc)
    : ecd_yaw(0.0)
    , ecd_pitch(0.0)
    , gyro_yaw(0.0)
    , gyro_pitch(0.0)
    , yaw_rate(0.0)
    , pitch_rate(0.0)  {
  (void)_alloc;
    }



   typedef double _ecd_yaw_type;
  _ecd_yaw_type ecd_yaw;

   typedef double _ecd_pitch_type;
  _ecd_pitch_type ecd_pitch;

   typedef double _gyro_yaw_type;
  _gyro_yaw_type gyro_yaw;

   typedef double _gyro_pitch_type;
  _gyro_pitch_type gyro_pitch;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef double _pitch_rate_type;
  _pitch_rate_type pitch_rate;





  typedef boost::shared_ptr< ::roborts_msgs::GimbalInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::GimbalInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalInfo_

typedef ::roborts_msgs::GimbalInfo_<std::allocator<void> > GimbalInfo;

typedef boost::shared_ptr< ::roborts_msgs::GimbalInfo > GimbalInfoPtr;
typedef boost::shared_ptr< ::roborts_msgs::GimbalInfo const> GimbalInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::GimbalInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de1cd11d7e2cb10eb47cdbc531727f86";
  }

  static const char* value(const ::roborts_msgs::GimbalInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde1cd11d7e2cb10eULL;
  static const uint64_t static_value2 = 0xb47cdbc531727f86ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/GimbalInfo";
  }

  static const char* value(const ::roborts_msgs::GimbalInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ecd_yaw\n\
float64 ecd_pitch\n\
float64 gyro_yaw\n\
float64 gyro_pitch\n\
float64 yaw_rate\n\
float64 pitch_rate\n\
";
  }

  static const char* value(const ::roborts_msgs::GimbalInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ecd_yaw);
      stream.next(m.ecd_pitch);
      stream.next(m.gyro_yaw);
      stream.next(m.gyro_pitch);
      stream.next(m.yaw_rate);
      stream.next(m.pitch_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::GimbalInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::GimbalInfo_<ContainerAllocator>& v)
  {
    s << indent << "ecd_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.ecd_yaw);
    s << indent << "ecd_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.ecd_pitch);
    s << indent << "gyro_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_yaw);
    s << indent << "gyro_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_pitch);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "pitch_rate: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GIMBALINFO_H
