// Generated by gencpp from file roborts_msgs/GimbalPID.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GIMBALPID_H
#define ROBORTS_MSGS_MESSAGE_GIMBALPID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct GimbalPID_
{
  typedef GimbalPID_<ContainerAllocator> Type;

  GimbalPID_()
    : is_valid(false)
    , yaw_mode(false)
    , pitch_mode(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , undetected_count_(0)  {
    }
  GimbalPID_(const ContainerAllocator& _alloc)
    : is_valid(false)
    , yaw_mode(false)
    , pitch_mode(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , undetected_count_(0)  {
  (void)_alloc;
    }



   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef uint8_t _yaw_mode_type;
  _yaw_mode_type yaw_mode;

   typedef uint8_t _pitch_mode_type;
  _pitch_mode_type pitch_mode;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef int32_t _undetected_count__type;
  _undetected_count__type undetected_count_;





  typedef boost::shared_ptr< ::roborts_msgs::GimbalPID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::GimbalPID_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalPID_

typedef ::roborts_msgs::GimbalPID_<std::allocator<void> > GimbalPID;

typedef boost::shared_ptr< ::roborts_msgs::GimbalPID > GimbalPIDPtr;
typedef boost::shared_ptr< ::roborts_msgs::GimbalPID const> GimbalPIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::GimbalPID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::GimbalPID_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalPID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalPID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalPID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47363277c60e8bf4c4fc3528d560ba62";
  }

  static const char* value(const ::roborts_msgs::GimbalPID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47363277c60e8bf4ULL;
  static const uint64_t static_value2 = 0xc4fc3528d560ba62ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/GimbalPID";
  }

  static const char* value(const ::roborts_msgs::GimbalPID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#detection to gimbal control\n\
bool is_valid\n\
bool yaw_mode\n\
bool pitch_mode\n\
float64 x\n\
float64 y\n\
float64 z\n\
int32 undetected_count_\n\
";
  }

  static const char* value(const ::roborts_msgs::GimbalPID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_valid);
      stream.next(m.yaw_mode);
      stream.next(m.pitch_mode);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.undetected_count_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalPID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::GimbalPID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::GimbalPID_<ContainerAllocator>& v)
  {
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "yaw_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yaw_mode);
    s << indent << "pitch_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pitch_mode);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "undetected_count_: ";
    Printer<int32_t>::stream(s, indent + "  ", v.undetected_count_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GIMBALPID_H
