// Generated by gencpp from file roborts_msgs/ShooterCmd.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_SHOOTERCMD_H
#define ROBORTS_MSGS_MESSAGE_SHOOTERCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct ShooterCmd_
{
  typedef ShooterCmd_<ContainerAllocator> Type;

  ShooterCmd_()
    : is_shoot(false)
    , shoot_cmd(0)
    , c_shoot_cmd(0)
    , fric_wheel_run(0)
    , shoot_freq(0)  {
    }
  ShooterCmd_(const ContainerAllocator& _alloc)
    : is_shoot(false)
    , shoot_cmd(0)
    , c_shoot_cmd(0)
    , fric_wheel_run(0)
    , shoot_freq(0)  {
  (void)_alloc;
    }



   typedef uint8_t _is_shoot_type;
  _is_shoot_type is_shoot;

   typedef uint8_t _shoot_cmd_type;
  _shoot_cmd_type shoot_cmd;

   typedef uint8_t _c_shoot_cmd_type;
  _c_shoot_cmd_type c_shoot_cmd;

   typedef uint8_t _fric_wheel_run_type;
  _fric_wheel_run_type fric_wheel_run;

   typedef uint16_t _shoot_freq_type;
  _shoot_freq_type shoot_freq;





  typedef boost::shared_ptr< ::roborts_msgs::ShooterCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::ShooterCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ShooterCmd_

typedef ::roborts_msgs::ShooterCmd_<std::allocator<void> > ShooterCmd;

typedef boost::shared_ptr< ::roborts_msgs::ShooterCmd > ShooterCmdPtr;
typedef boost::shared_ptr< ::roborts_msgs::ShooterCmd const> ShooterCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::ShooterCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ShooterCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ShooterCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ShooterCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ce874438e33b75dd468a5f9109af925";
  }

  static const char* value(const ::roborts_msgs::ShooterCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ce874438e33b75dULL;
  static const uint64_t static_value2 = 0xd468a5f9109af925ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/ShooterCmd";
  }

  static const char* value(const ::roborts_msgs::ShooterCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_shoot\n\
uint8 shoot_cmd\n\
uint8 c_shoot_cmd\n\
uint8 fric_wheel_run\n\
uint16 shoot_freq\n\
";
  }

  static const char* value(const ::roborts_msgs::ShooterCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_shoot);
      stream.next(m.shoot_cmd);
      stream.next(m.c_shoot_cmd);
      stream.next(m.fric_wheel_run);
      stream.next(m.shoot_freq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShooterCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::ShooterCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::ShooterCmd_<ContainerAllocator>& v)
  {
    s << indent << "is_shoot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_shoot);
    s << indent << "shoot_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shoot_cmd);
    s << indent << "c_shoot_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.c_shoot_cmd);
    s << indent << "fric_wheel_run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fric_wheel_run);
    s << indent << "shoot_freq: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shoot_freq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_SHOOTERCMD_H
