// Generated by gencpp from file roborts_msgs/Target.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_TARGET_H
#define ROBORTS_MSGS_MESSAGE_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct Target_
{
  typedef Target_<ContainerAllocator> Type;

  Target_()
    : id(0)
    , state(0)
    , sensor(0)
    , x(0.0)
    , y(0.0)
    , confidence(0.0)  {
    }
  Target_(const ContainerAllocator& _alloc)
    : id(0)
    , state(0)
    , sensor(0)
    , x(0.0)
    , y(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _sensor_type;
  _sensor_type sensor;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::roborts_msgs::Target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::Target_<ContainerAllocator> const> ConstPtr;

}; // struct Target_

typedef ::roborts_msgs::Target_<std::allocator<void> > Target;

typedef boost::shared_ptr< ::roborts_msgs::Target > TargetPtr;
typedef boost::shared_ptr< ::roborts_msgs::Target const> TargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::Target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::Target_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::Target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::Target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::Target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::Target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::Target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::Target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efa7f772ad165e48d9a6bd49c109d98a";
  }

  static const char* value(const ::roborts_msgs::Target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefa7f772ad165e48ULL;
  static const uint64_t static_value2 = 0xd9a6bd49c109d98aULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/Target";
  }

  static const char* value(const ::roborts_msgs::Target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8 state\n\
uint8 sensor\n\
float32 x\n\
float32 y\n\
float32 confidence\n\
";
  }

  static const char* value(const ::roborts_msgs::Target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::Target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.state);
      stream.next(m.sensor);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::Target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::Target_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_TARGET_H
