// Generated by gencpp from file roborts_msgs/TargetInfo.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_TARGETINFO_H
#define ROBORTS_MSGS_MESSAGE_TARGETINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct TargetInfo_
{
  typedef TargetInfo_<ContainerAllocator> Type;

  TargetInfo_()
    : is_valid(false)
    , id(0)
    , bbox()
    , pose()
    , optical_flow()  {
    }
  TargetInfo_(const ContainerAllocator& _alloc)
    : is_valid(false)
    , id(0)
    , bbox(_alloc)
    , pose(_alloc)
    , optical_flow(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _bbox_type;
  _bbox_type bbox;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pose_type;
  _pose_type pose;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _optical_flow_type;
  _optical_flow_type optical_flow;





  typedef boost::shared_ptr< ::roborts_msgs::TargetInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::TargetInfo_<ContainerAllocator> const> ConstPtr;

}; // struct TargetInfo_

typedef ::roborts_msgs::TargetInfo_<std::allocator<void> > TargetInfo;

typedef boost::shared_ptr< ::roborts_msgs::TargetInfo > TargetInfoPtr;
typedef boost::shared_ptr< ::roborts_msgs::TargetInfo const> TargetInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::TargetInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::TargetInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/lichangheng/robo_ws/Decision/RoboRTS_decision/devel/share/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg', '/home/lichangheng/robo_ws/Decision/RoboRTS_decision/src/roborts_msgs/msg/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::TargetInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::TargetInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::TargetInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "332308c6498382ae0ac339a429da4973";
  }

  static const char* value(const ::roborts_msgs::TargetInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x332308c6498382aeULL;
  static const uint64_t static_value2 = 0x0ac339a429da4973ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/TargetInfo";
  }

  static const char* value(const ::roborts_msgs::TargetInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_valid\n\
uint8 id\n\
float32[] bbox\n\
float32[] pose\n\
float32[] optical_flow\n\
";
  }

  static const char* value(const ::roborts_msgs::TargetInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_valid);
      stream.next(m.id);
      stream.next(m.bbox);
      stream.next(m.pose);
      stream.next(m.optical_flow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::TargetInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::TargetInfo_<ContainerAllocator>& v)
  {
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "bbox[]" << std::endl;
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      s << indent << "  bbox[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bbox[i]);
    }
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pose[i]);
    }
    s << indent << "optical_flow[]" << std::endl;
    for (size_t i = 0; i < v.optical_flow.size(); ++i)
    {
      s << indent << "  optical_flow[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.optical_flow[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_TARGETINFO_H
